export const ROLES = {
  CUSTOMER: "CUSTOMER",
  TELLER: "TELLER",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  ADMIN: "ADMIN",
};

export const STAFF_ROLES = [ROLES.TELLER, ROLES.BRANCH_MANAGER, ROLES.ADMIN];
